### ISSUE TITLE
Main Tag container blocks user interaction with webpage

### ISSUE THREAD

**Issue by okramovic** [Otto-AA/Tag#9]
how about not setting the height of main Tag container as it was till now (min-height=100vh) to leaving it empty/auto, so this panel doesnt block normal user interaction with page? bcs its also quite wide..

**Comment by Otto-AA** [comment]
Yes you can do that. I don't think it is that important as I would hide it by default for the release (you too?) but still nice :)

**Comment by okramovic** [comment]
it can be hidden by default ofc, but even when i do want tags to be visible, panel should not take the whole height and block user interaction. i removed the height of tag-fixed-right-panel in css
